language: go
addons:
  apt:
    packages:
    - pv
go:
- '1.14'
- tip
script:
- make ci
- pv -q -L 175 test/testoutput.txt | make run
before_deploy: 
- make archives
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
deploy:
  provider: releases
  edge: true
  api_key:
    secure: KAqC9I/FF93eA5Sthfk5W6ju3YZBx0aSUkf2UcAImrR4prFRLKr8d9q+x/MNkbDet5OyYazlUElrjoSfO8yTn6J+mLu3bvvmRSInZx/8mQ4D3Vd+Snl+dpMe/zgoeu8HcTsEF9bo+nvCMsIMdQeW0WbzbrLvs/WIRC9d4J+japymQlyU/Vf1dj7NUD6P5lA6Xiz8ucgMH3RYCsXBpahQxnSnQRXOXyjpkpSWLVUHuc8lnmmrbKELrHdFW1O7pPON7YPQDumGwv+64deRKf42aki7G5tdKhTof01P4ut4JaZIeeFFX3N8QGX4MyL3+crtljPp6iVOn1l1XO3gfavAN62ULoqL72F4F98wkZbnG3bVV9YYwNLEYbIo80bH+/LgGkd3mT9uzTDIIn87szlVDPcWfTs0FbZ7KedMc/mjb4xIYf4KynKDnkWxBAInRmPIeZXZ8I33wYYXM4gqwJ0TF/qbPSsRPnq4QkD5raj0RjI2iwoZ/cZu3dGQ0h1ClKIKeyAsMpGR4HINV4bvICrj12gWB62ekkFy0m1YGif74X2lyAVpdIxm8LcDrjwXSwwmhHY4zgJxBwPPIMIo6lo4FjX6JvC1t8C6/Ii0HxZsA3KUtVZoTxon68yZM1IOrPxjYvrbOV1dWsbUkLYy2u0X9lc5I9d921XifXWM8ucdpts=
  cleanup: false
  file_glob: true
  file: artifacts/archives/*
  on:
    tags: true
